/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrincosCategoriaBrincoRouteImport } from './routes/brincos/$categoriaBrinco'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrincosCategoriaBrincoRoute = BrincosCategoriaBrincoRouteImport.update({
  id: '/brincos/$categoriaBrinco',
  path: '/brincos/$categoriaBrinco',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brincos/$categoriaBrinco': typeof BrincosCategoriaBrincoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brincos/$categoriaBrinco': typeof BrincosCategoriaBrincoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brincos/$categoriaBrinco': typeof BrincosCategoriaBrincoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brincos/$categoriaBrinco'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brincos/$categoriaBrinco'
  id: '__root__' | '/' | '/brincos/$categoriaBrinco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrincosCategoriaBrincoRoute: typeof BrincosCategoriaBrincoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brincos/$categoriaBrinco': {
      id: '/brincos/$categoriaBrinco'
      path: '/brincos/$categoriaBrinco'
      fullPath: '/brincos/$categoriaBrinco'
      preLoaderRoute: typeof BrincosCategoriaBrincoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrincosCategoriaBrincoRoute: BrincosCategoriaBrincoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
