/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColaresCategoriaColarRouteImport } from './routes/colares/$categoriaColar'
import { Route as BrincosCategoriaBrincoRouteImport } from './routes/brincos/$categoriaBrinco'
import { Route as AneisCategoriaAnelRouteImport } from './routes/aneis/$categoriaAnel'
import { Route as CategoriasTodosIndexRouteImport } from './routes/categorias/todos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaresCategoriaColarRoute = ColaresCategoriaColarRouteImport.update({
  id: '/colares/$categoriaColar',
  path: '/colares/$categoriaColar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrincosCategoriaBrincoRoute = BrincosCategoriaBrincoRouteImport.update({
  id: '/brincos/$categoriaBrinco',
  path: '/brincos/$categoriaBrinco',
  getParentRoute: () => rootRouteImport,
} as any)
const AneisCategoriaAnelRoute = AneisCategoriaAnelRouteImport.update({
  id: '/aneis/$categoriaAnel',
  path: '/aneis/$categoriaAnel',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasTodosIndexRoute = CategoriasTodosIndexRouteImport.update({
  id: '/categorias/todos/',
  path: '/categorias/todos/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aneis/$categoriaAnel': typeof AneisCategoriaAnelRoute
  '/brincos/$categoriaBrinco': typeof BrincosCategoriaBrincoRoute
  '/colares/$categoriaColar': typeof ColaresCategoriaColarRoute
  '/categorias/todos/': typeof CategoriasTodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aneis/$categoriaAnel': typeof AneisCategoriaAnelRoute
  '/brincos/$categoriaBrinco': typeof BrincosCategoriaBrincoRoute
  '/colares/$categoriaColar': typeof ColaresCategoriaColarRoute
  '/categorias/todos': typeof CategoriasTodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aneis/$categoriaAnel': typeof AneisCategoriaAnelRoute
  '/brincos/$categoriaBrinco': typeof BrincosCategoriaBrincoRoute
  '/colares/$categoriaColar': typeof ColaresCategoriaColarRoute
  '/categorias/todos/': typeof CategoriasTodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aneis/$categoriaAnel'
    | '/brincos/$categoriaBrinco'
    | '/colares/$categoriaColar'
    | '/categorias/todos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aneis/$categoriaAnel'
    | '/brincos/$categoriaBrinco'
    | '/colares/$categoriaColar'
    | '/categorias/todos'
  id:
    | '__root__'
    | '/'
    | '/aneis/$categoriaAnel'
    | '/brincos/$categoriaBrinco'
    | '/colares/$categoriaColar'
    | '/categorias/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AneisCategoriaAnelRoute: typeof AneisCategoriaAnelRoute
  BrincosCategoriaBrincoRoute: typeof BrincosCategoriaBrincoRoute
  ColaresCategoriaColarRoute: typeof ColaresCategoriaColarRoute
  CategoriasTodosIndexRoute: typeof CategoriasTodosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colares/$categoriaColar': {
      id: '/colares/$categoriaColar'
      path: '/colares/$categoriaColar'
      fullPath: '/colares/$categoriaColar'
      preLoaderRoute: typeof ColaresCategoriaColarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brincos/$categoriaBrinco': {
      id: '/brincos/$categoriaBrinco'
      path: '/brincos/$categoriaBrinco'
      fullPath: '/brincos/$categoriaBrinco'
      preLoaderRoute: typeof BrincosCategoriaBrincoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aneis/$categoriaAnel': {
      id: '/aneis/$categoriaAnel'
      path: '/aneis/$categoriaAnel'
      fullPath: '/aneis/$categoriaAnel'
      preLoaderRoute: typeof AneisCategoriaAnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/todos/': {
      id: '/categorias/todos/'
      path: '/categorias/todos'
      fullPath: '/categorias/todos/'
      preLoaderRoute: typeof CategoriasTodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AneisCategoriaAnelRoute: AneisCategoriaAnelRoute,
  BrincosCategoriaBrincoRoute: BrincosCategoriaBrincoRoute,
  ColaresCategoriaColarRoute: ColaresCategoriaColarRoute,
  CategoriasTodosIndexRoute: CategoriasTodosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
